blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('add/', views.PostAdd.as_view(), name='post_add'),
    path('upload/', views.upload, name='upload'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('本文')

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.core.files.storage import default_storage
from .models import Post
from .widgets import FileUploadableTextArea


class PostForm(forms.ModelForm):
    """記事の追加フォーム"""

    class Meta:
        model = Post
        fields = '__all__'
        widgets = {
            'text': FileUploadableTextArea,
        }


class FileUploadForm(forms.Form):
    """ファイルのアップロードフォーム"""
    file = forms.FileField()

    def save(self):
        upload_file = self.cleaned_data['file']
        file_name = default_storage.save(upload_file.name, upload_file)
        file_url = default_storage.url(file_name)
        return file_url

blog/views.py
from django.http import HttpResponseBadRequest, JsonResponse
from django.urls import reverse_lazy
from django.views import generic
from .forms import FileUploadForm, PostForm
from .models import Post


class PostList(generic.ListView):
    """記事一覧"""
    model = Post


class PostDetail(generic.DetailView):
    """記事詳細"""
    model = Post


class PostAdd(generic.CreateView):
    """記事の追加。実際には、ログイン者だけ使えるようにする、等してください。"""
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:post_list')


def upload(request):
    """ファイルのアップロード用ビュー"""
    form = FileUploadForm(files=request.FILES)
    if form.is_valid():
        url = form.save()
        return JsonResponse({'url': url})
    return HttpResponseBadRequest()

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>ブログ</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <a href="{% url 'blog:post_list' %}">記事一覧</a>
    <h1>{{ post.title }}</h1>
    <p>{{ post.text | safe }}</p>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <a href="{% url 'blog:post_list' %}">記事一覧</a>
    <h1>記事の追加</h1>
    <form action="" method="POST">
        {{ form.as_p }}
        {{ form.media }}
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <a href="{% url 'blog:post_add' %}">記事追加</a>
    <h1>記事一覧</h1>
    {% for post in post_list %}
        <p><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></p>
    {% endfor %}
{% endblock %}